services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        USER_ID: '${WWWUSER:-1000}'
#        GROUP_ID: '${WWWGROUP:-1000}'
#        USER: '${USER:-whoami}'
    container_name: app
    restart: always
    working_dir: /var/www/
#    command: sh -c "
#      cd /var/www/backend
#      kill -USR2 1
#      "
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../:/var/www

  db:
    container_name: db
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
