networks:
  application:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../:/var/www
    command: ["sh", "./docker/entrypoint.sh"]
    networks:
      - application

  db:
    container_name: db
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
    networks:
      - application
    ports:
      - "3306:3306"
