services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        USER_ID: '${WWWUSER:-1000}'
#        GROUP_ID: '${WWWGROUP:-1000}'
#        USER: '${USER:-whoami}'
    container_name: app
    restart: always
    working_dir: /var/www/
#    command: sh -c "
#      cd /var/www/backend
#      kill -USR2 1
#      "
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../:/var/www
    command: php backend/artisan serve --host=0.0.0.0 --port=8000
